### ISSUE TITLE
Cannot write cookie when installing Rabbit.

### ISSUE THREAD

**Issue by BDuduk** [thycotic/rabbitmq-helper#32]
Operation failed with: Failed to copy system cookie: System cookie path not found in 
C:\Windows\System32\config\systemprofile\.erlang.cookie. Installation may fail.. Manual deletion might be 
necessary;System cookie path not found in C:\Windows\System32\config\systemprofile\.erlang.cookie. Installation may 
fail.;. Would you like to Retry? 
[Y] Yes [N] No [S] Suspend [?] Help (default is "Y"):

The workaround for this was to delete the cookie and force the retry. This would generate the new cookie and allow the installation process to proceed.

Permission issue. If there is no cookie/file by that name, cookie write is successful.

**Comment by afalahi** [comment]
@bharaba the cookie is flagged as read-only in the file system, unchecking that box solves the issue.

**Comment by bharaba** [comment]
Fixed with read-only attribute removal.
