### ISSUE TITLE
RabbitMQ-Uninstall does not remove a Directory in %AppData%\Roaming\RabbitMQ, which can cause re-installation to fail.

### ISSUE THREAD

**Issue by andycrandall** [thycotic/rabbitmq-helper#40]
Hello, after doing a few full RabbitMQ uninstall / re-installs recently to upgrade RabbitMQ / Erlang versions, I've noticed that in the Uninstall-RabbitMQ command (rabbitmq-helper/src/Thycotic.RabbitMq.Helper.PSCommands/Installation/UninstallRabbitMqCommand.cs)
The CleanUpFolders() method only removes items from the explicit Install Directory, and the Site Connector folder in the Thycotic Software LTD directories.

From: (rabbitmq-helper/src/Thycotic.RabbitMq.Helper.PSCommands/Installation/UninstallRabbitMqCommand.cs)

`

        private void CleanUpFolders(string installPath)
        {
            var directoryCleaner = new DirectoryCleaner();
            try
            {
                directoryCleaner.Clean(installPath);
            }
            catch (Exception ex)
            {
                WriteWarning("Failed to clean installation path. Clean removal might fail: " + ex.Message);
            }

            try
            {
                directoryCleaner.Clean(InstallationConstants.RabbitMq.ConfigurationPath);
            }
            catch (Exception ex)
            {
                WriteWarning("Failed to clean configuration path. Clean removal might fail: " + ex.Message);
            }
        }  `

These Items are set in (rabbitmq-helper/src/Thycotic.RabbitMq.Helper.Logic/InstallationConstants.cs): 

`

            /// <summary>
            ///     The configuration path
            /// </summary>
          public static readonly string ConfigurationPath = Path.Combine(EnvironmentalVariables.ProgramFiles,
                "Thycotic Software Ltd", "RabbitMq Site Connector");

            /// <summary>
            ///     The install path
            /// </summary>
            public static readonly string InstallPath = Path.Combine(EnvironmentalVariables.ProgramFiles,
                "RabbitMQ Server", "rabbitmq_server-3.7.5");

`

Now the issue here, is that the RabbitMQ installation, also drops files and configuration items into "C:\Users\Username\AppData\Roaming\RabbitMQ", and when a reinstall of RabbitMQ is initiated, it appears that the service references this folder with old information, as opposed to a newly created one.

Adding a couple lines to the InstallationConstants.cs, and referencing those in UninstallRabbitMQCommands.cs could potentially resolve these issues we are seeing. At this point, we have to remove that folder from AppData manually, and then perform a reboot, to which the install will typically continue smoothly.

 What is extra odd to me, is that there doesn't seem to be any information of value in the \AppData\Roaming\RabbitMQ folder, but consistently, when we run into issues, and then we remove this folder, then reboot the installation succeeds without issue.

Please let me know if there's any clarification you need, or if there's anything else I can do to help out on this!

**Comment by bharaba** [comment]
Fix put in but may still warn if permissions fails.
