### ISSUE TITLE
RabbitMQ installation will not complete with FIPS enabled

### ISSUE THREAD

**Issue by jarredrandolph** [thycotic/rabbitmq-helper#54]
When FIPS is enabled on the server you are installing RabbitMQ on using the helper you will get this error:

"Exception has been thrown by the target of an invocation.;This implementation is not part of the 
Windows Platform FIPS validated cryptographic algorithms"

After you disable FIPS temporarily you can complete the installation and then go back and re-enable FIPS.

**Comment by JeremyThycotic** [comment]
Seems to be due to verifying downloads using MD5 hashes - switching to SHA1 should fix this.

**Comment by bharaba** [comment]
Will be using SHA512.

**Comment by bharaba** [comment]
Resolved in latest version.
