### ISSUE TITLE
non-prompt mode for Install-Connector on RabbitMQ

### ISSUE THREAD

**Issue by edarko2000** [thycotic/rabbitmq-helper#57]
Hello All,
      The new version of Install-Connector https://thycotic.github.io/rabbitmq-helper/usecases/installation/ broke the automation installation of client's script since in the final step it need to open the management UI- "Open-RabbitMqManagement - Open the RabbitMQ management UI" . In the non-prompt mode,  the script doesn't have the inter-active mode so it thought the install command failed. This was not happening in the old version 6.x
Any way/parameter to disable it to avoid opening the  RabbitMQ management UI in the end?

If there’s the way to turn off this launching the management UI (through installation parameter of any configure file), that will be great.

As I understand, this is bug as opening the management should be optional. Thank you.

**Comment by bharaba** [comment]
I'm going to add a try catch around the command to catch is issue as well as any other problems that can cause the browser not to open. The result will be a warning output but the command will not fail.

**Comment by bharaba** [comment]
Resolved in latest version.
