### ISSUE TITLE
Downloads fail without -Force option

### ISSUE THREAD

**Issue by JeremyThycotic** [thycotic/rabbitmq-helper#60]
If a download has failed (i.e. AV software blocks it but creates a 0 byte file, or a download is interrupted etc), the -Force option must be used to trigger a re-download. Without -Force, the download commands seem to be happy that the file already exists even though the checksum is off. Should check the file checksum and re-download automatically without the -Force option if the pre-existing file does not match the expected checksum.

**Comment by bharaba** [comment]
The file checksum is always checked and re-download begins. Please try again on latest version and report findings.

**Comment by bharaba** [comment]
Closing due to lack of response. Re-validated working.
