### ISSUE TITLE
SSL install always fails because port 5672 is checked at end of install

### ISSUE THREAD

**Issue by MatthewHerrmann** [thycotic/rabbitmq-helper#66]
SSL install always fails because port 5672 is checked at end of install. When I go to SS and validate 5671, the install is correct. I imagine port 5671 should be checked when Rabbit is installed using SSL, or there is some other problem causing the install to report failure.

If you close the helper and open the management console, the installs where the helper seems to fail on SSL (all of them) are fine - they just report failure because it can't get a good connection to Rabbit.

**Comment by bharaba** [comment]
Fixed in 8.0.0.12
