### ISSUE TITLE
Assert-RabbitMqConnectivity fails against SSL Rabbit

### ISSUE THREAD

**Issue by MatthewHerrmann** [thycotic/rabbitmq-helper#69]
Assert-RabbitMqConnectivity fails against SSL Rabbit using the suggested powershell script and adding -UseTLS and -port 5671, or any combination of the two. 

The rabbit is currently working my application, so I know that it is on and available, and the test was performed from the same machine as the Rabbit, so a Rabbit connectivity issue is unlikely.

**Comment by bharaba** [comment]
I tried reproducing this but it doesn't appear to be an issue. Are you specifying the FQDN of the rabbit node?

**Comment by bharaba** [comment]
Fixed in 8.0.0.12
